---
# NOTE: That didn't work, thus use of instance with nested virtualization enabled.

compute_engine_instance:
  image_project: cirrus-images
  image: family/docker-kvm
  platform: linux
  cpu: 4
  memory: 16G
  disk: 100
  nested_virtualization: true

#env:
#  S3CMD_ACCESS_KEY:
#  S3CMD_BUCKET:
#  S3CMD_HOST:
#  S3CMD_SECRET_KEY:

build_task:
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION
    populate_script: python3 -m pip install --upgrade setuptools wheel

  pip_script:
    - pip install --upgrade pip