---
compute_engine_instance:
  image_project: cirrus-images
  image: family/docker-kvm
  platform: linux
  cpu: 4
  memory: 16G
  disk: 100
  nested_virtualization: true

env:
  MINIO_ACCESS_KEY: "ENCRYPTED[!c85a5b06195e06226b58d4942dfe82c8732f74994b5dd4015f0d4dccad36a7e2b28120429366b69bb3bd2cd85b1cb5ab!]"
  MINIO_SECRET_KEY: "ENCRYPTED[!af79fd66b5d6cdde7aab229041fe45b422a22d7dc315b08fb7f8b7eb6c612b78156c27270ca230501874c4bd1705a8ca!]"

build_task:
  install_script:
    - apt-get update
    - apt-get install -y python3-pip
    - pip3 install -r requirements.txt
    - wget https://dl.min.io/client/mc/release/linux-amd64/mc
    - chmod +x mc
    - ./mc alias set minio https://minio.services.osism.tech $MINIO_ACCESS_KEY $MINIO_SECRET_KEY

  build_generic_images_script:
    - ironic-python-agent-builder -o ./ipa-ubuntu --release focal -e dynamic-login -e extra-hardware ubuntu
    - ironic-python-agent-builder -o ./ipa-centos --release 8 -e dynamic-login -e extra-hardware centos

  build_burn_in_images_script:
    - ironic-python-agent-builder -o ./ipa-burnin-ubuntu --release focal -e dynamic-login -e extra-hardware -e burn-in ubuntu
    - ironic-python-agent-builder -o ./ipa-burnin-centos --release 8 -e dynamic-login -e extra-hardware -e burn-in centos

  build_proliant_images_script:
    - ironic-python-agent-builder -o ./ipa-proliant-ubuntu --release focal -e dynamic-login -e extra-hardware -e burn-in -e proliant-tools ubuntu
    - ironic-python-agent-builder -o ./ipa-proliant-centos --release 8 -e dynamic-login -e extra-hardware -e burn-in -e proliant-tools centos

  push_script: |
    if [ "$CIRRUS_BRANCH" == "main" ]; then
      ./mc policy set download minio/openstack-ironic-ipa-images
    fi
